/***** Project Header *****/
// Project Name:
// Version: 1
// Author:
// Date: 22/9/2019  5:14
// Code auto-generated by systemdesignerjs
//      from www.techideas.co.nz

/***** Includes *****/
#include <Arduino.h>

/***** Hardware macros *****/
//WRITE YOUR MACRO DEFINITIONS HERE
#define PI 3.14
#define LED_1_PIN 13
#define LED_2_PIN 27
#define LED_3_PIN 25
#define LED_4_PIN 14
#define LED_5_PIN 12
#define LED_6_PIN 26

#define LED_8_PIN 17
#define LED_9_PIN 16
#define LED_10_PIN 18
#define LED_11_PIN 22
#define LED_12_PIN 19
#define LED_13_PIN 4
#define LED_14_PIN 15

/***** Declare & initialise global variables *****/

/***** Run once code goes here *****/
void setup()
{
    /***** IO Hardware Config *****/
    //WRITE YOUR SETUP CODE HERE
    pinMode(LED_1_PIN, OUTPUT);
    pinMode(LED_2_PIN, OUTPUT);
    pinMode(LED_3_PIN, OUTPUT);
    pinMode(LED_4_PIN, OUTPUT);
    pinMode(LED_5_PIN, OUTPUT);
    pinMode(LED_6_PIN, OUTPUT);

    pinMode(LED_8_PIN, OUTPUT);
    pinMode(LED_9_PIN, OUTPUT);
    pinMode(LED_10_PIN, OUTPUT);
    pinMode(LED_11_PIN, OUTPUT);
    pinMode(LED_12_PIN, OUTPUT);
    pinMode(LED_13_PIN, OUTPUT);
    pinMode(LED_14_PIN, OUTPUT);
} //setup end

void display(int hours, int mins)
{
    //COMPLETE THIS FUNTION
    int hr10 = (hours / 10) % 10;
    int hr1 = hours % 10;

    int min10 = (mins / 10) % 10;
    int min1 = mins % 10;

    if (hr10 == 0)
    {
        digitalWrite(LED_1_PIN, LOW);
        digitalWrite(LED_2_PIN, LOW);
    }
    if (hr10 == 1)
    {
        digitalWrite(LED_1_PIN, HIGH);
        digitalWrite(LED_2_PIN, LOW);
    }
    if (hr10 == 2)
    {
        digitalWrite(LED_1_PIN, LOW);
        digitalWrite(LED_2_PIN, HIGH);
    }

    if (hr1 == 0)
    {
        digitalWrite(LED_3_PIN, LOW);
        digitalWrite(LED_4_PIN, LOW);
        digitalWrite(LED_5_PIN, LOW);
        digitalWrite(LED_6_PIN, LOW);
    }
    if (hr1 == 1)
    {
        digitalWrite(LED_3_PIN, HIGH);
        digitalWrite(LED_4_PIN, LOW);
        digitalWrite(LED_5_PIN, LOW);
        digitalWrite(LED_6_PIN, LOW);
    }
    if (hr1 == 2)
    {
        digitalWrite(LED_3_PIN, LOW);
        digitalWrite(LED_4_PIN, HIGH);
        digitalWrite(LED_5_PIN, LOW);
        digitalWrite(LED_6_PIN, LOW);
    }
    if (hr1 == 3)
    {
        digitalWrite(LED_3_PIN, HIGH);
        digitalWrite(LED_4_PIN, HIGH);
        digitalWrite(LED_5_PIN, LOW);
        digitalWrite(LED_6_PIN, LOW);
    }
    if (hr1 == 4)
    {
        digitalWrite(LED_3_PIN, LOW);
        digitalWrite(LED_4_PIN, LOW);
        digitalWrite(LED_5_PIN, HIGH);
        digitalWrite(LED_6_PIN, LOW);
    }
    if (hr1 == 5)
    {
        digitalWrite(LED_3_PIN, HIGH);
        digitalWrite(LED_4_PIN, LOW);
        digitalWrite(LED_5_PIN, HIGH);
        digitalWrite(LED_6_PIN, LOW);
    }
    if (hr1 == 6)
    {
        digitalWrite(LED_3_PIN, LOW);
        digitalWrite(LED_4_PIN, HIGH);
        digitalWrite(LED_5_PIN, HIGH);
        digitalWrite(LED_6_PIN, LOW);
    }
    if (hr1 == 7)
    {
        digitalWrite(LED_3_PIN, HIGH);
        digitalWrite(LED_4_PIN, HIGH);
        digitalWrite(LED_5_PIN, HIGH);
        digitalWrite(LED_6_PIN, LOW);
    }
    if (hr1 == 8)
    {
        digitalWrite(LED_3_PIN, LOW);
        digitalWrite(LED_4_PIN, LOW);
        digitalWrite(LED_5_PIN, LOW);
        digitalWrite(LED_6_PIN, HIGH);
    }
    if (hr1 == 9)
    {
        digitalWrite(LED_3_PIN, HIGH);
        digitalWrite(LED_4_PIN, LOW);
        digitalWrite(LED_5_PIN, LOW);
        digitalWrite(LED_6_PIN, HIGH);
    }

    //MINUTES

    if (min10 == 0)
    {
        digitalWrite(LED_8_PIN, LOW);
        digitalWrite(LED_9_PIN, LOW);
        digitalWrite(LED_10_PIN, LOW);
    }
    if (min10 == 1)
    {
        digitalWrite(LED_8_PIN, HIGH);
        digitalWrite(LED_9_PIN, LOW);
        digitalWrite(LED_10_PIN, LOW);
    }
    if (min10 == 2)
    {
        digitalWrite(LED_8_PIN, LOW);
        digitalWrite(LED_9_PIN, HIGH);
        digitalWrite(LED_10_PIN, LOW);
    }
    if (min10 == 3)
    {
        digitalWrite(LED_8_PIN, HIGH);
        digitalWrite(LED_9_PIN, HIGH);
        digitalWrite(LED_10_PIN, LOW);
    }
    if (min10 == 4)
    {
        digitalWrite(LED_8_PIN, LOW);
        digitalWrite(LED_9_PIN, LOW);
        digitalWrite(LED_10_PIN, HIGH);
    }
    if (min10 == 5)
    {
        digitalWrite(LED_8_PIN, HIGH);
        digitalWrite(LED_9_PIN, LOW);
        digitalWrite(LED_10_PIN, HIGH);
    }

    if (min1 == 0)
    {
        digitalWrite(LED_11_PIN, LOW);
        digitalWrite(LED_12_PIN, LOW);
        digitalWrite(LED_13_PIN, LOW);
        digitalWrite(LED_14_PIN, LOW);
    }
    if (min1 == 1)
    {
        digitalWrite(LED_11_PIN, HIGH);
        digitalWrite(LED_12_PIN, LOW);
        digitalWrite(LED_13_PIN, LOW);
        digitalWrite(LED_14_PIN, LOW);
    }
    if (min1 == 2)
    {
        digitalWrite(LED_11_PIN, LOW);
        digitalWrite(LED_12_PIN, HIGH);
        digitalWrite(LED_13_PIN, LOW);
        digitalWrite(LED_14_PIN, LOW);
    }
    if (min1 == 3)
    {
        digitalWrite(LED_11_PIN, HIGH);
        digitalWrite(LED_12_PIN, HIGH);
        digitalWrite(LED_13_PIN, LOW);
        digitalWrite(LED_14_PIN, LOW);
    }
    if (min1 == 4)
    {
        digitalWrite(LED_11_PIN, LOW);
        digitalWrite(LED_12_PIN, LOW);
        digitalWrite(LED_13_PIN, HIGH);
        digitalWrite(LED_14_PIN, LOW);
    }
    if (min1 == 5)
    {
        digitalWrite(LED_11_PIN, HIGH);
        digitalWrite(LED_12_PIN, LOW);
        digitalWrite(LED_13_PIN, HIGH);
        digitalWrite(LED_14_PIN, LOW);
    }
    if (min1 == 6)
    {
        digitalWrite(LED_11_PIN, LOW);
        digitalWrite(LED_12_PIN, HIGH);
        digitalWrite(LED_13_PIN, HIGH);
        digitalWrite(LED_14_PIN, LOW);
    }
    if (min1 == 7)
    {
        digitalWrite(LED_11_PIN, HIGH);
        digitalWrite(LED_12_PIN, HIGH);
        digitalWrite(LED_13_PIN, HIGH);
        digitalWrite(LED_14_PIN, LOW);
    }
    if (min1 == 8)
    {
        digitalWrite(LED_11_PIN, LOW);
        digitalWrite(LED_12_PIN, LOW);
        digitalWrite(LED_13_PIN, LOW);
        digitalWrite(LED_14_PIN, HIGH);
    }
    if (min1 == 9)
    {
        digitalWrite(LED_11_PIN, HIGH);
        digitalWrite(LED_12_PIN, LOW);
        digitalWrite(LED_13_PIN, LOW);
        digitalWrite(LED_14_PIN, HIGH);
    }
}

//***** Loop code *****/
void loop()
{

    /***** Actions *****/
    // DO NOT CHANGE OR ADD ANY CODE TO THIS loop
    // when the program is run,
    // this will cycle all the LEDs to display 4 different times
    //this will create a unique test for ther LEDs
    delay(1000);
    display(14, 21);
    delay(1000);
    display(2, 42);
    delay(1000);
    display(21, 58);
    delay(1000);
    display(8, 14);

} //loop end

/***** Functions *****/